parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/'
        exclude: '../src/App/Kernel.php'

    Modules\Invoices\:
        resource: '../src/Modules/Invoices/'

    Modules\Notifications\:
        resource: '../src/Modules/Notifications/'

    Modules\Invoices\Domain\Repositories\InvoiceRepositoryInterface:
        alias: Modules\Invoices\Infrastructure\Repositories\DoctrineInvoiceRepository

    Modules\Notifications\Api\NotificationFacadeInterface:
        alias: Modules\Notifications\Application\Facades\NotificationFacade

    Modules\Notifications\Infrastructure\Drivers\DriverInterface:
        alias: Modules\Notifications\Infrastructure\Drivers\DummyDriver
