invoices_create:
    path: /invoices
    controller: Modules\Invoices\Presentation\Http\InvoiceController::create
    methods: [POST]

invoices_view:
    path: /invoices/{id}
    controller: Modules\Invoices\Presentation\Http\InvoiceController::view
    methods: [GET]
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

invoices_send:
    path: /invoices/{id}/send
    controller: Modules\Invoices\Presentation\Http\InvoiceController::send
    methods: [POST]
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
