notification_hook:
    path: /notification/hook/{action}/{reference}
    controller: Modules\Notifications\Presentation\Http\NotificationController::hook
    methods: [GET]
    requirements:
        action: '[a-zA-Z]+'
        reference: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
